### PR TITLE
Add JSFoo, 2017 conference 

### PR DESCRIPTION
**Pull request by kalpeshsingh**
**Details of the conference**:

- Website:
- Date:
- Venue:
- Description:

### CODE REVIEW

**Comment by nikhita** [comment]
Thank you for your contribution! :smile: 

There are a few folks who watch this repo so that the PR description gives them information about the conf directly. So to include that,

- Website: https://jsfoo.in/2017/
- Date: 15-16 Sep
- Venue: MLR Convention Centre, Brigade Millenium Complex, Bengaluru
- Description: JSFoo is India’s premier JavaScript conference, hosted by HasGeek. The broad theme this year is building reliable web apps.

**Comment by kalpeshsingh** [comment]
Any action needed from my side?

**Comment by nikhita** [comment]
No, no action is needed. It's already pretty great that you contributed! :)

**Comment by kalpeshsingh** [comment]
Awesome! :)

**Pull request merged**
