### PR TITLE
Add DevOps Days India 2017

### PR DESCRIPTION
**Pull request by arush-sal**

### CODE REVIEW

**Comment by nikhita** [comment]
Looks great, thank you for your contribution! :smile:

**Comment by arush-sal** [comment]
Wow! That was fast :flushed:
Anyway, nice idea. Hope I won't miss GopherCon 2018 thanks to this.

**Comment by nikhita** [comment]
Haha please don't miss! I would be attending Gophercon India 2018 as well and would love to meet you!

PS: Are you going to be at GopherCon Denver next month?

**Comment by arush-sal** [comment]
Well, Denver is about 13526 KMs from my place, will cost me ₹1,26,000 just for the tickets and would require me to have a Visa and Passport. So, seems it will by Grace Hopper Conf. :rofl:

**Comment by nikhita** [comment]
Haha see you at GopherCon India 2018 then! :joy:

**Comment by arush-sal** [comment]
Indeed! :+1:

**Pull request merged**
