### PR TITLE
Add GopherCon '18

### PR DESCRIPTION
**Pull request by arush-sal**
**Details of the conference**: GopherCon '18

- Website: www.gophercon.in
- Date: 9-10 Mar 2018
- Venue: Sheraton Grand , sangamvadi, Pune
- Description: Go conference in India. Go is an open source project developed by a team at Google and many contributors from the open source community.

### CODE REVIEW

**Comment by nikhita** [comment]
@arush-sal Woah, nice to see the 2018 GopherCon India already kicking off! :tada: 

Thanks for adding this! :)

**Comment by maknahar** [comment]
Are date and venue confirmed for GopherCon 2018? I do not see any information online or on https://github.com/golang/go/wiki/Conferences. 😕

**Comment by nikhita** [comment]
@maknahar The date and venue were tweeted from the official GopherCon India account. https://twitter.com/GopherConIndia/status/880647136865636361. Also, this information was posted on the #gophercon-india channel on Gophers slack by the organizer.

I think it has not been updated on the wiki yet because the website http://www.gophercon.in/ still shows the 2017 information.

I'll talk to the organizer if it can be added to the wiki. Thanks for notifying about this! :smile:

**Comment by arush-sal** [comment]
@maknahar Adding to @nikhita's comment, the information is updated at and was taken from the event registration page: https://www.townscript.com/e/gci18

**Comment by nikhita** [comment]
@maknahar @arush-sal I talked to the organizer. The website will be updated soon. I'll add it in the wiki once the website is updated. :+1:

**Comment by maknahar** [comment]
Thanks, @nikhita and @arush-sal

**Pull request merged**
