### PR TITLE
feat: Add India OS

### PR DESCRIPTION
**Pull request by mr-karan**
**Details of the conference**:

- Website: https://indiaos.in/
- Date: 18 Jan 2020
- Venue: Zerodha, #175/176, Next to Rainbow Hospital, Bengaluru 
- Description: India Open Source is a free and non-commercial community event. The goal is to provide software developers and policy makers, communities and enthusiasts a platform to meet and interact. We want to see IndiaOS to grow as a platform to share and grow open source projects and to foster the values of open source in modern software development

### CODE REVIEW

**Comment by nikhita** [comment]
@mr-karan By any chance, are you one of the organizers for this conference? The website doesn't seem to include any contact info, but I noticed that you work at Zerodha (one of the sponsors for the event).

This repo requires conferences to include a CFP and a Code of Conduct (CoC). I just realized that IndiaOS doesn't have a CoC in place, so I shouldn't have merged this right away.

If you are an organizer, could you please make sure that a CoC is added for the conference and is accessible on the website? Having a CoC will also be helpful to attendees for reasons I won't dive into here. :)

I'll wait for ~1 week for the CoC to be added. If a CoC doesn't exist by then, I'll need to revert this PR.

fyi @gouthamve

**Comment by aravindputrevu** [comment]
This looks like a great event @mr-karan 
Feel free to let me know if there is a way we can support it. 

Also thanks @nikhita for the CoC part.

**Comment by mr-karan** [comment]
@nikhita I'm not the organizer, but I will pass on the message to them, thanks!

**Comment by scmmishra** [comment]
@nikhita thanks for the review. I'm one of the organizers of IndiaOS, We are adding the CoC soon, perhaps will be deployed in a couple of days.

**Comment by nikhita** [comment]
@scmmishra Perfect! Thanks a lot for the quick response! :)

**Pull request merged**
