### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SaashaJoshi**
**Data Hack Summit**:

- Website: https://www.analyticsvidhya.com/datahack-summit-2018/?utm_source=kdnuggets
- Date: 22-24 Nov 2018
- Venue:  NIMHANS Convention Centre, Bengaluru
- Description: India's most advanced conference on Aritificial Intelligence, Machine Learning, Deep Learning and IoT

### CODE REVIEW

**Comment by nikhita** [comment]
@SaashaJoshi Does this conference have CFPs?

This repo only accepts conferences which have CFPs. From a quick glance at the website, it doesn't look like the conference allows CFPs.

Can you point me to a link to the CFP if it does? Happy to merge if that's the case. :)

**Comment by SaashaJoshi** [comment]
Yes, they are inviting papers and talks for the summit. 
Ref: https://docs.google.com/forms/d/e/1FAIpQLSfWBb3jhmbdNFb7lOpImS-oKkGgqVtP07PM1nePlOjra0AYwg/viewform

**Comment by SaashaJoshi** [comment]
Open Call for Conference Speakers & Research Papers! Present a talk at DataHack Summit 2018 – Most Influential Conference of 2018 in Artificial Intelligence, Machine Learning & IOT. DHS2018 also invites submission of papers describing innovative research on all aspects of data science. Apply for nominations here: https://goo.gl/forms/9wLvo0s02d0zcvvy2

**Comment by SaashaJoshi** [comment]
No issues! Thanks for merging!! :)

**Pull request merged**
