### PR TITLE
Add JS Channel Conference

### PR DESCRIPTION
**Pull request by nikhita**
Details:

- Website: http://2017.jschannel.com/
- Date: 28-29 July
- Venue: JW Marriott Hotel, Bengaluru
- Description: JS Channel is a unique platform to hear best of the bests speakers in JS Community along with learning from expert JS trainers in workshop/live-coding sessions.

### CODE REVIEW

**Comment by allurimanojvarma** [comment]
Details of the conference:

Website: https://www.hdcon.org
Date: 03 Feb 2018
Venue: Hyderabad
Description: Hosting and Domain Conference is the World's Top initiative to discuss on latest happenings in the field of web technologies. Its an 1 day event. Over 2000 Delegates along with 30 Speakers participate in this conference.Hosting, Domain, Blogging and Web technologies are major discussions.

**Comment by nikhita** [comment]
@allurimanojvarma thank you! Can you open a PR for this conference? If not, I'll add it myself. Let me know what you prefer. :smile:

**Comment by allurimanojvarma** [comment]
Please add it yourself. Thank you :)

**Comment by allurimanojvarma** [comment]
Nikhita can you get the conference added to the list.

**Comment by shivakrishna9** [comment]
@allurimanojvarma I added it as a PR.
@nikhita  Please review and merge it.

**Comment by allurimanojvarma** [comment]
Thank you Shiva

**Comment by nikhita** [comment]
@allurimanojvarma Sorry, didn't find time over the week to do it. Was going to get to it at the weekend. But @shivakrishna9 got to it first. :)

Thanks for the PR, @shivakrishna9!

**Pull request merged**
