### PR TITLE
Reverse Chronological order of Conferences

### PR DESCRIPTION
**Pull request by cnu**
Displaying the events/conferences in a reverse chronological order
within each year makes it easier to quickly search for which events
are remaining in an year.
This also makes sure that the latest information is available with
minimal scrolling.

### CODE REVIEW

**Comment by nikhita** [comment]
Sounds good. :+1: 

One minor change - Can you change the sentence in the [Contributing section](https://github.com/nikhita/tech-conferences-india#contributing-) from `Please make sure that the conferences are in chronological order..` to `Please make sure that the conferences are in reverse chronological order..`?

(Github won't let me comment on the diff since this line is not part of the diff)

**Comment by nikhita** [comment]
Also, please squash commits after this. Thanks! :)

**Comment by nikhita** [comment]
@cnu Looks great! Can you squash the two commits to one commit?

**Comment by cnu** [comment]
Squashed.

**Comment by nikhita** [comment]
@cnu Oh no, looks like there is a merge conflict now. Can you rebase and fix them? Thanks!

**Comment by cnu** [comment]
@nikhita Rebased. 

Please merge this PR before accepting other events so that it would be easier for everyone to contribute.

**Comment by nikhita** [comment]
> Please merge this PR before accepting other events so that it would be easier for everyone to contribute.

:+1: 

Thanks for the refactoring!

**Pull request merged**
