### PR TITLE
Add Grace Hopper Celebration India (GHCI) 2017

### PR DESCRIPTION
**Pull request by arush-sal**
Add Grace Hopper Celebration India (GHCI) 2017 to be held on 16-17 Nov in Bengaluru. CFP closes 9th Jun, All the Best.

### CODE REVIEW

**Comment by nikhita** [comment]
You are on a roll today! Thanks for so many contributions!! :tada: :confetti_ball: 

Yes, I plan to submit a talk even though only a few days are left. Thanks for the reminder. :smile:

**Comment by arush-sal** [comment]
1. It's just two adds.
2. No, I am not on roll, I am frustrated and pissed on myself as HELL! That's why.
3. All the best(again)

**Comment by nikhita** [comment]
1. Even a typo fix is a GOOD contribution according to me.
2. Why, what happened? (if you don't mind sharing?)

**Comment by arush-sal** [comment]
Sorry, just saw the comment. BTW regarding "What happened", Already did that.

**Pull request merged**
